name: Health Check

on: 
  push:
    branches:
      - master

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
    - name: Check if the sevice URL is up
      uses: jtalk/url-health-check-action@v3
      with:
        url: 'https://fso-pokedex-7zia.onrender.com/'