name: Health Check

on: 
  schedule:
    - cron: '0 1 * 1 *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
    - name: Check if the sevice URL is up
      uses: jtalk/url-health-check-action@v3
      with:
        url: 'https://fso-pokedex-7zia.onrender.com/health'
    - name: Health Check Failure
      uses: rjstone/discord-webhook-notify@v1.0.4
      if: failure()
      with:
        severity: error
        username: Pokedex Health Check
        text: OH NO! there is somthing wrong with the pokedex!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
    - name: Health Check OK
      uses: rjstone/discord-webhook-notify@v1.0.4
      if: success()
      with:
        severity: info
        username: Pokedex Health Check
        text: Pokedex is online.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}